### ISSUE TITLE
Show list of executions

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp-insights#87] opened 2020-11-19 14:14 UTC
In order to ensure consistency, I would suggest that there be an executions table that shows that executions that have been done, with links to the results, algorithms and original datasets. Failed/successful and running executions should be shown in different colours, similar to the way it is done in CodeShip. In the future, users might be able to access and read logs from the executions this way.

**Comment by pyphilia** [comment] 2020-11-20 10:22
duplicate of #44

**Closed by pyphilia** 2020-11-20 10:22 UTC
Labels: enhancement
